org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
android.suppressUnsupportedCompileSdk=36
org.gradle.java.home=C:/Program Files/Java/jdk-21.0.11
WEBRTC_TURN_URL=turns:openrelay.metered.ca:443
WEBRTC_TURN_USERNAME=9048ae39ccfd45a09e53f5a5
WEBRTC_TURN_PASSWORD=akC+3M4g8nzKgqqJ
