org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
android.suppressUnsupportedCompileSdk=36
org.gradle.java.home=C:/Program Files/Java/jdk-21.0.11
WEBRTC_TURN_URL=turn:global.relay.metered.ca:80,turn:global.relay.metered.ca:80?transport=tcp,turn:global.relay.metered.ca:443,turns:global.relay.metered.ca:443?transport=tcp
WEBRTC_TURN_USERNAME=9048ae39ccfd45a09e53f5a5
WEBRTC_TURN_PASSWORD=akC+3M4g8nzKgqqJ
